name: Test

on:
  push:

jobs:
  test:
    timeout-minutes: 30
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          docker-compose build app
          docker-compose run --rm app
